### ISSUE TITLE
problem with "python -m pytest"

### ISSUE THREAD

**Issue by Npizza** [danpaquin/gdax-python#203]
i run the "python -m pytest" and i have this output:

`platform linux2 -- Python 2.7.12, pytest-3.3.1, py-1.5.2, pluggy-0.6.0
rootdir: /home/pizza/Desktop/gdax-python-master, inifile: pytest.ini
plugins: cov-2.5.1
collected 18 items                                                            

test_public_client.py .......F...F......                                [100%]Coverage.py warning: Module gdax/ was never imported. (module-not-imported)
Coverage.py warning: No data was collected. (no-data-collected)

================================== FAILURES ===================================
____ TestPublicClient.test_get_historic_rates[3600-2017-11-30-2017-11-01] _____

self = <test_public_client.TestPublicClient object at 0x7f8559e79610>
client = <gdax.public_client.PublicClient object at 0x7f8559e79050>
start = '2017-11-01', end = '2017-11-30', granularity = 3600

    @pytest.mark.parametrize('start', ('2017-11-01', None))
    @pytest.mark.parametrize('end', ('2017-11-30', None))
    @pytest.mark.parametrize('granularity', (3600, None))
    def test_get_historic_rates(self, client, start, end, granularity):
        r = client.get_product_historic_rates('BTC-USD', start=start, end=end, granularity=granularity)
>       assert type(r) is list
E       AssertionError: assert <type 'dict'> is list
E        +  where <type 'dict'> = type({'message': 'granularity too small for the requested time range'})

test_public_client.py:54: AssertionError
------------------------------ Captured log call ------------------------------
connectionpool.py          818 DEBUG    Starting new HTTPS connection (1): api.gdax.com
connectionpool.py          395 DEBUG    https://api.gdax.com:443 "GET /products/BTC-USD/candles?start=2017-11-01&end=2017-11-30&granularity=3600 HTTP/1.1" 400 64
____ TestPublicClient.test_get_historic_rates[None-2017-11-30-2017-11-01] _____

self = <test_public_client.TestPublicClient object at 0x7f85595eee10>
client = <gdax.public_client.PublicClient object at 0x7f8559e79050>
start = '2017-11-01', end = '2017-11-30', granularity = None

    @pytest.mark.parametrize('start', ('2017-11-01', None))
    @pytest.mark.parametrize('end', ('2017-11-30', None))
    @pytest.mark.parametrize('granularity', (3600, None))
    def test_get_historic_rates(self, client, start, end, granularity):
        r = client.get_product_historic_rates('BTC-USD', start=start, end=end, granularity=granularity)
>       assert type(r) is list
E       AssertionError: assert <type 'dict'> is list
E        +  where <type 'dict'> = type({'message': 'granularity too small for the requested time range'})

test_public_client.py:54: AssertionError
------------------------------ Captured log call ------------------------------
connectionpool.py          818 DEBUG    Starting new HTTPS connection (1): api.gdax.com
connectionpool.py          395 DEBUG    https://api.gdax.com:443 "GET /products/BTC-USD/candles?start=2017-11-01&end=2017-11-30 HTTP/1.1" 400 64
==================== 2 failed, 16 passed in 16.10 seconds =====================
ERROR: Failed to generate report: No data to report.

`

what i have to look? I am new and i am a little bit lost

**Comment by acontry** [comment]
I'm the original author of these tests - thanks for running them to see if they still work :). Looks like GDAX is unhappy because this is requesting more than 200 data points in one request. One month of candles with hour granularity is 30*24 points. To fix, the time range must be decreased or granularity period increased. For example, changing granularity to 3600*24 (to get 24hr granularity) should fix the test.

**Comment by Npizza** [comment]
i did this change to the test_public_client.py file:
`    @pytest.mark.parametrize('granularity', (3600*24, None))`
and it didn't worked
it printed 
`============================= test session starts =============================
platform linux2 -- Python 2.7.12, pytest-3.3.1, py-1.5.2, pluggy-0.6.0
rootdir: /home/pizza/Desktop/gdax-python-master, inifile: pytest.ini
plugins: cov-2.5.1
collected 18 items                                                            

test_public_client.py ...........F......                                [100%]Coverage.py warning: Module gdax/ was never imported. (module-not-imported)
Coverage.py warning: No data was collected. (no-data-collected)


================================== FAILURES ===================================
____ TestPublicClient.test_get_historic_rates[None-2017-11-30-2017-11-01] _____

self = <test_public_client.TestPublicClient object at 0x7fe763da72d0>
client = <gdax.public_client.PublicClient object at 0x7fe764601090>
start = '2017-11-01', end = '2017-11-30', granularity = None

    @pytest.mark.parametrize('start', ('2017-11-01', None))
    @pytest.mark.parametrize('end', ('2017-11-30', None))
    @pytest.mark.parametrize('granularity', (3600*24, None))
    def test_get_historic_rates(self, client, start, end, granularity):
        r = client.get_product_historic_rates('BTC-USD', start=start, end=end, granularity=granularity)
>       assert type(r) is list
E       AssertionError: assert <type 'dict'> is list
E        +  where <type 'dict'> = type({'message': 'granularity too small for the requested time range'})

test_public_client.py:54: AssertionError
------------------------------ Captured log call ------------------------------
connectionpool.py          818 DEBUG    Starting new HTTPS connection (1): api.gdax.com
connectionpool.py          395 DEBUG    https://api.gdax.com:443 "GET /products/BTC-USD/candles?start=2017-11-01&end=2017-11-30 HTTP/1.1" 400 64
==================== 1 failed, 17 passed in 21.92 seconds =====================
ERROR: Failed to generate report: No data to report.
`


did i understood correct what you are trying to say?

**Comment by acontry** [comment]
Yeah that was my guess, but looks like it didn't work. Another idea is that the dates are in ISO 8601 format as documented in GDAX API, but they actually might need to be datetimes (ie. YYYY-MM-DDTHH:MM:SS).

**Comment by Npizza** [comment]
i change it to 
`
    @pytest.mark.parametrize('start', ('2017-11-0112:00:00', None))
    @pytest.mark.parametrize('end', ('2017-11-3012:00:00', None))
    @pytest.mark.parametrize('granularity', (3600*24, None))`

the problem still exists
`pytest============================= test session starts =============================
platform linux2 -- Python 2.7.12, pytest-3.3.1, py-1.5.2, pluggy-0.6.0
rootdir: /home/pizza/Desktop/gdax-python-master, inifile: pytest.ini
plugins: cov-2.5.1
collected 18 items                                                            

test_public_client.py .......F...F......                                [100%]Coverage.py warning: Module gdax/ was never imported. (module-not-imported)
Coverage.py warning: No data was collected. (no-data-collected)


================================== FAILURES ===================================
 TestPublicClient.test_get_historic_rates[86400-2017-11-3012:00:00-2017-11-0112:00:00] 

self = <test_public_client.TestPublicClient object at 0x7f5a7cf75e90>
client = <gdax.public_client.PublicClient object at 0x7f5a7cf58a50>
start = '2017-11-0112:00:00', end = '2017-11-3012:00:00', granularity = 86400

    @pytest.mark.parametrize('start', ('2017-11-0112:00:00', None))
    @pytest.mark.parametrize('end', ('2017-11-3012:00:00', None))
    @pytest.mark.parametrize('granularity', (3600*24, None))
    def test_get_historic_rates(self, client, start, end, granularity):
        r = client.get_product_historic_rates('BTC-USD', start=start, end=end, granularity=granularity)
>       assert type(r) is list
E       AssertionError: assert <type 'dict'> is list
E        +  where <type 'dict'> = type({'message': 'Invalid interval'})

test_public_client.py:54: AssertionError
------------------------------ Captured log call ------------------------------
connectionpool.py          818 DEBUG    Starting new HTTPS connection (1): api.gdax.com
connectionpool.py          395 DEBUG    https://api.gdax.com:443 "GET /products/BTC-USD/candles?start=2017-11-0112%3A00%3A00&end=2017-11-3012%3A00%3A00&granularity=86400 HTTP/1.1" 400 30
 TestPublicClient.test_get_historic_rates[None-2017-11-3012:00:00-2017-11-0112:00:00] 

self = <test_public_client.TestPublicClient object at 0x7f5a7c6e5f50>
client = <gdax.public_client.PublicClient object at 0x7f5a7cf58a50>
start = '2017-11-0112:00:00', end = '2017-11-3012:00:00', granularity = None

    @pytest.mark.parametrize('start', ('2017-11-0112:00:00', None))
    @pytest.mark.parametrize('end', ('2017-11-3012:00:00', None))
    @pytest.mark.parametrize('granularity', (3600*24, None))
    def test_get_historic_rates(self, client, start, end, granularity):
        r = client.get_product_historic_rates('BTC-USD', start=start, end=end, granularity=granularity)
>       assert type(r) is list
E       AssertionError: assert <type 'dict'> is list
E        +  where <type 'dict'> = type({'message': 'Invalid interval'})

test_public_client.py:54: AssertionError
------------------------------ Captured log call ------------------------------
connectionpool.py          818 DEBUG    Starting new HTTPS connection (1): api.gdax.com
connectionpool.py          395 DEBUG    https://api.gdax.com:443 "GET /products/BTC-USD/candles?start=2017-11-0112%3A00%3A00&end=2017-11-3012%3A00%3A00 HTTP/1.1" 400 30
==================== 2 failed, 16 passed in 16.68 seconds =====================
ERROR: Failed to generate report: No data to report.
`

**Comment by acontry** [comment]
You're missing the letter "T" in the format (ex. "2007-04-05T14:30").

**Comment by Npizza** [comment]
i did this 
`
    @pytest.mark.parametrize('start', ('2007-04-05T14:30', None))
    @pytest.mark.parametrize('end', ('2007-04-06T14:30', None))
    @pytest.mark.parametrize('granularity', (3600*24, None))`


the same problem
`============================= test session starts =============================
platform linux2 -- Python 2.7.12, pytest-3.3.1, py-1.5.2, pluggy-0.6.0
rootdir: /home/pizza/Desktop/gdax-python-master, inifile: pytest.ini
plugins: cov-2.5.1
collected 18 items                                                            

test_public_client.py ...........F......                                [100%]Coverage.py warning: Module gdax/ was never imported. (module-not-imported)
Coverage.py warning: No data was collected. (no-data-collected)


================================== FAILURES ===================================
 TestPublicClient.test_get_historic_rates[None-2007-04-06T14:30-2007-04-05T14:30] 

self = <test_public_client.TestPublicClient object at 0x7f2e18d017d0>
client = <gdax.public_client.PublicClient object at 0x7f2e195b40d0>
start = '2007-04-05T14:30', end = '2007-04-06T14:30', granularity = None

    @pytest.mark.parametrize('start', ('2007-04-05T14:30', None))
    @pytest.mark.parametrize('end', ('2007-04-06T14:30', None))
    @pytest.mark.parametrize('granularity', (3600*24, None))
    def test_get_historic_rates(self, client, start, end, granularity):
        r = client.get_product_historic_rates('BTC-USD', start=start, end=end, granularity=granularity)
>       assert type(r) is list
E       AssertionError: assert <type 'dict'> is list
E        +  where <type 'dict'> = type({'message': 'granularity too small for the requested time range'})

test_public_client.py:54: AssertionError
------------------------------ Captured log call ------------------------------
connectionpool.py          818 DEBUG    Starting new HTTPS connection (1): api.gdax.com
connectionpool.py          395 DEBUG    https://api.gdax.com:443 "GET /products/BTC-USD/candles?start=2007-04-05T14%3A30&end=2007-04-06T14%3A30 HTTP/1.1" 400 64
==================== 1 failed, 17 passed in 14.45 seconds =====================
ERROR: Failed to generate report: No data to report.

`

**Comment by alimcmaster1** [comment]
I propose the following fix for this handing in datetimes to the testcase.
https://github.com/danpaquin/gdax-python/pull/207/commits/ff07566a0d381d8ee043e597f3adaf432eaae741

What do you guys think?

Thanks AM

**Comment by acontry** [comment]
Thanks for the fix! Anything to get things working is fine with me.
